### PR TITLE
Added the latest version of my slides and some additional reading mat…

### PR DESCRIPTION
**Pull request by odysseaspenta**
…erials

### CODE REVIEW

**Comment by chemodan** [comment]
Odysseas, let me know if you want me to merge your changes or you're going
to take care of it

**Comment by chemodan** [comment]
Odysseas, let me know if you want me to merge your changes or if you are going to take care of it yourself.   Thanks!

**Comment by odysseaspenta** [comment]
Alex,

Can you please merge in those files for me?

Thanks,
Odysseas

**Comment by chemodan** [comment]
Done; sorry the travel took me longer than I thought.  Please let me know if it all looks good on your end after the merge.

**Comment by odysseaspenta** [comment]
Alex,
It looks fine to me. Thanks for doing this. I didn't think I had access to
the repository to do it myself.

Odysseas Pentakalos, Ph.D., PMP
Chief Technology Officer
SYSNET International, Inc.
2930 Oak Shadow Drive
Oak Hill, Virginia 20171
odysseas@sysnetint.com
(703) 855-2029

**Pull request merged**
